import { ComplaintItem, DepartmentInfo, NotificationItem, SystemAuditLog, UserProfile, UserRole } from './types';
import { CATEGORY_MAP } from './ai/vision-service';
import { calculateAIPriorityScore } from './ai/priority-engine';

export const INITIAL_DEPARTMENTS: DepartmentInfo[] = [
  {
    id: 'dept-pwd',
    code: 'PWD',
    name: 'Public Works Department',
    headOfficer: 'Er. Rajesh Varma (Chief Engineer)',
    contactEmail: 'pwd.helpdesk@civiclens.gov.in',
    contactPhone: '+91 11 2345 6789',
    slaHours: 48,
    activeTickets: 42,
    resolvedTickets: 380,
    avgResolutionDays: 1.8,
  },
  {
    id: 'dept-mc',
    code: 'MUNICIPAL_CORP',
    name: 'Municipal Corporation Sanitation',
    headOfficer: 'Dr. Sunita Sharma (Sanitation Commissioner)',
    contactEmail: 'sanitation@civiclens.gov.in',
    contactPhone: '+91 11 2345 8899',
    slaHours: 24,
    activeTickets: 68,
    resolvedTickets: 920,
    avgResolutionDays: 0.9,
  },
  {
    id: 'dept-water',
    code: 'WATER',
    name: 'Water Supply & Sewerage Board',
    headOfficer: 'Ir. Vikramaditya Roy',
    contactEmail: 'waterboards@civiclens.gov.in',
    contactPhone: '+91 11 2345 1122',
    slaHours: 36,
    activeTickets: 31,
    resolvedTickets: 450,
    avgResolutionDays: 1.2,
  },
  {
    id: 'dept-elec',
    code: 'ELECTRICITY',
    name: 'Electricity & Public Lighting Dept',
    headOfficer: 'Er. Amit Kulkarni',
    contactEmail: 'powergrid@civiclens.gov.in',
    contactPhone: '+91 11 2345 3344',
    slaHours: 24,
    activeTickets: 25,
    resolvedTickets: 510,
    avgResolutionDays: 0.8,
  },
  {
    id: 'dept-traffic',
    code: 'TRAFFIC',
    name: 'Traffic Police & Road Infrastructure',
    headOfficer: 'DCP Ananya Singh',
    contactEmail: 'traffic.cell@civiclens.gov.in',
    contactPhone: '+91 11 2345 5566',
    slaHours: 12,
    activeTickets: 18,
    resolvedTickets: 290,
    avgResolutionDays: 0.5,
  },
  {
    id: 'dept-drainage',
    code: 'DRAINAGE',
    name: 'Drainage & Stormwater Board',
    headOfficer: 'Er. Suresh Mehta',
    contactEmail: 'drainage@civiclens.gov.in',
    contactPhone: '+91 11 2345 7788',
    slaHours: 24,
    activeTickets: 55,
    resolvedTickets: 640,
    avgResolutionDays: 1.1,
  },
];

export const DEMO_USERS: Record<UserRole, UserProfile> = {
  CITIZEN: {
    id: 'usr-citizen-01',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    role: 'CITIZEN',
    reputationScore: 480,
    tier: 'GOLD',
    resolvedCount: 14,
    reportedCount: 18,
  },
  AUTHORITY: {
    id: 'usr-auth-01',
    name: 'Officer Rajesh Varma',
    email: 'rajesh.varma@pwd.gov.in',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    role: 'AUTHORITY',
    reputationScore: 1250,
    tier: 'VERIFIED_REPORTER',
    departmentCode: 'PWD',
    departmentName: 'Public Works Department',
    resolvedCount: 142,
    reportedCount: 5,
  },
  ADMIN: {
    id: 'usr-admin-01',
    name: 'Admin Chief Controller',
    email: 'admin.director@civiclens.gov.in',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    role: 'ADMIN',
    reputationScore: 2500,
    tier: 'VERIFIED_REPORTER',
    resolvedCount: 520,
    reportedCount: 2,
  },
};

export const INITIAL_COMPLAINTS: ComplaintItem[] = [
  {
    id: 'cmp-001',
    ticketId: 'TICK-ROAD-8841',
    title: 'Hazardous Deep Pothole Matrix Near City Hospital Gate 2',
    description: 'Multiple deep crater potholes on main arterial road leading directly to City General Hospital emergency ambulance bay. Causing severe traffic bottlenecks and ambulance delays.',
    category: 'ROAD_DAMAGE',
    categoryLabel: CATEGORY_MAP.ROAD_DAMAGE.label,
    severity: 'CRITICAL',
    status: 'IN_PROGRESS',
    priorityScore: 96,
    confidenceScore: 0.98,
    reportCount: 187,
    isDuplicate: false,
    citizenId: 'usr-citizen-01',
    citizenName: 'Aarav Mehta',
    citizenAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    assignedEngineerId: 'eng-101',
    assignedEngineerName: 'Er. Ramesh Kumar (Senior PWD Inspector)',
    departmentCode: 'PWD',
    departmentName: 'Public Works Department',
    location: {
      address: 'MG Road, Opposite City General Hospital, Gate 2',
      ward: 'Ward 8 (Old City Market)',
      zone: 'Central Zone',
      latitude: 28.6139,
      longitude: 77.2090,
      nearHospital: true,
      nearSchool: false,
      trafficDensity: 'HIGH',
    },
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      detectedCategory: 'ROAD_DAMAGE',
      categoryLabel: CATEGORY_MAP.ROAD_DAMAGE.label,
      severityScore: 94,
      riskLevel: 'CRITICAL',
      confidenceScore: 0.98,
      impactAssessment: 'High speed vehicular axle damage and critical ambulance transport disruption.',
      suggestedDepartmentCode: 'PWD',
      suggestedDepartmentName: 'Public Works Department',
      suggestedAction: 'Immediate hot-mix asphalt filling and roller compaction within 12 hours.',
    },
    upvotes: 142,
    hasUpvoted: true,
    commentsCount: 28,
    history: [
      {
        id: 'h-1',
        status: 'PENDING',
        actorName: 'Aarav Mehta (Citizen)',
        note: 'Complaint submitted with high-res photo.',
        timestamp: '2026-08-07T14:30:00Z',
      },
      {
        id: 'h-2',
        status: 'PENDING',
        actorName: 'AI Spatial Merge Engine',
        note: 'Merged 186 duplicate citizen reports in 150m radius. Priority score escalated to 96/100.',
        timestamp: '2026-08-07T15:10:00Z',
      },
      {
        id: 'h-3',
        status: 'IN_PROGRESS',
        actorName: 'Er. Rajesh Varma (PWD Head)',
        note: 'Assigned to Senior PWD Inspector Er. Ramesh Kumar. Crew dispatched with asphalt batch unit.',
        timestamp: '2026-08-07T16:00:00Z',
      },
    ],
    createdAt: '2026-08-07T14:30:00Z',
    updatedAt: '2026-08-07T16:00:00Z',
  },
  {
    id: 'cmp-002',
    ticketId: 'TICK-DRAIN-4421',
    title: 'Severe Stormwater Drain Obstruction & Foul Water Spill',
    description: 'Blocked main arterial drainage line causing foul water backflow onto residential street outside St. Xavier Public School.',
    category: 'DRAINAGE_PROBLEM',
    categoryLabel: CATEGORY_MAP.DRAINAGE_PROBLEM.label,
    severity: 'CRITICAL',
    status: 'ASSIGNED',
    priorityScore: 91,
    confidenceScore: 0.95,
    reportCount: 64,
    isDuplicate: false,
    citizenId: 'usr-citizen-02',
    citizenName: 'Priya Sharma',
    citizenAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    assignedEngineerId: 'eng-104',
    assignedEngineerName: 'Er. Vikram Patel (Drainage Specialist)',
    departmentCode: 'DRAINAGE',
    departmentName: 'Drainage & Stormwater Board',
    location: {
      address: 'School Road, Near St. Xavier Academy',
      ward: 'Ward 8 (Old City Market)',
      zone: 'Central Zone',
      latitude: 28.6160,
      longitude: 77.2120,
      nearHospital: false,
      nearSchool: true,
      trafficDensity: 'HIGH',
    },
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      detectedCategory: 'DRAINAGE_PROBLEM',
      categoryLabel: CATEGORY_MAP.DRAINAGE_PROBLEM.label,
      severityScore: 90,
      riskLevel: 'CRITICAL',
      confidenceScore: 0.95,
      impactAssessment: 'School student pedestrian exposure to contaminated waterlogging.',
      suggestedDepartmentCode: 'DRAINAGE',
      suggestedDepartmentName: 'Drainage & Stormwater Board',
      suggestedAction: 'Deploy high-pressure hydraulic jetting truck.',
    },
    upvotes: 89,
    hasUpvoted: false,
    commentsCount: 14,
    history: [
      {
        id: 'h-201',
        status: 'PENDING',
        actorName: 'Priya Sharma (Citizen)',
        note: 'Reported via voice transcript in Hinglish.',
        timestamp: '2026-08-07T11:00:00Z',
      },
      {
        id: 'h-202',
        status: 'ASSIGNED',
        actorName: 'Drainage Desk Officer',
        note: 'Dispatched to Er. Vikram Patel.',
        timestamp: '2026-08-07T13:20:00Z',
      },
    ],
    createdAt: '2026-08-07T11:00:00Z',
    updatedAt: '2026-08-07T13:20:00Z',
  },
  {
    id: 'cmp-003',
    ticketId: 'TICK-GARB-3312',
    title: 'Massive Unattended Solid Waste Accumulation',
    description: 'Overloaded municipal garbage bins overflowing onto pedestrian pavement near Central Metro Station Gate 3.',
    category: 'GARBAGE_OVERFLOW',
    categoryLabel: CATEGORY_MAP.GARBAGE_OVERFLOW.label,
    severity: 'HIGH',
    status: 'CITIZEN_VERIFICATION',
    priorityScore: 84,
    confidenceScore: 0.96,
    reportCount: 42,
    isDuplicate: false,
    citizenId: 'usr-citizen-03',
    citizenName: 'Rohan Verma',
    citizenAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    assignedEngineerId: 'eng-108',
    assignedEngineerName: 'Sanitation Supervisor Sunil Gupta',
    departmentCode: 'MUNICIPAL_CORP',
    departmentName: 'Municipal Corporation Sanitation',
    location: {
      address: 'Station Plaza, Metro Gate 3',
      ward: 'Ward 5 (Station Junction)',
      zone: 'South Zone',
      latitude: 28.6210,
      longitude: 77.2180,
      nearHospital: false,
      nearSchool: false,
      trafficDensity: 'HIGH',
    },
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    afterImageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      detectedCategory: 'GARBAGE_OVERFLOW',
      categoryLabel: CATEGORY_MAP.GARBAGE_OVERFLOW.label,
      severityScore: 82,
      riskLevel: 'HIGH',
      confidenceScore: 0.96,
      impactAssessment: 'High density pedestrian transit zone aesthetic and sanitation breakdown.',
      suggestedDepartmentCode: 'MUNICIPAL_CORP',
      suggestedDepartmentName: 'Municipal Corporation Sanitation',
      suggestedAction: 'Clear waste bin and spray disinfectant.',
    },
    proofOfWork: {
      beforeImageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
      afterImageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
      officialNotes: 'Compactor truck #MC-44 deployed. Area thoroughly sanitized with bleaching powder spray.',
      aiVerificationScore: 0.96,
      resolvedByEngineer: 'Supervisor Sunil Gupta',
      timestamp: '2026-08-07T18:00:00Z',
    },
    upvotes: 56,
    hasUpvoted: false,
    commentsCount: 9,
    history: [
      {
        id: 'h-301',
        status: 'PENDING',
        actorName: 'Rohan Verma (Citizen)',
        note: 'Submitted via Civic Lens App.',
        timestamp: '2026-08-07T08:00:00Z',
      },
      {
        id: 'h-302',
        status: 'CITIZEN_VERIFICATION',
        actorName: 'Supervisor Sunil Gupta',
        note: 'Uploaded Proof-of-Work after image. Awaiting citizen confirmation.',
        timestamp: '2026-08-07T18:00:00Z',
      },
    ],
    createdAt: '2026-08-07T08:00:00Z',
    updatedAt: '2026-08-07T18:00:00Z',
  },
  {
    id: 'cmp-004',
    ticketId: 'TICK-LIGHT-9102',
    title: 'Inoperative High-Mast Streetlight Array at Junction',
    description: 'Blackout on 4-way traffic intersection creating severe nighttime collision risk.',
    category: 'BROKEN_STREETLIGHT',
    categoryLabel: CATEGORY_MAP.BROKEN_STREETLIGHT.label,
    severity: 'MEDIUM',
    status: 'PENDING',
    priorityScore: 68,
    confidenceScore: 0.91,
    reportCount: 15,
    isDuplicate: false,
    citizenId: 'usr-citizen-01',
    citizenName: 'Aarav Mehta',
    citizenAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    departmentCode: 'ELECTRICITY',
    departmentName: 'Electricity & Public Lighting Dept',
    location: {
      address: 'Outer Ring Junction, Ward 2',
      ward: 'Ward 2 (Civil Lines)',
      zone: 'North Zone',
      latitude: 28.6280,
      longitude: 77.2010,
      nearHospital: false,
      nearSchool: false,
      trafficDensity: 'MODERATE',
    },
    imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      detectedCategory: 'BROKEN_STREETLIGHT',
      categoryLabel: CATEGORY_MAP.BROKEN_STREETLIGHT.label,
      severityScore: 65,
      riskLevel: 'MEDIUM',
      confidenceScore: 0.91,
      impactAssessment: 'Nighttime intersection visibility reduction.',
      suggestedDepartmentCode: 'ELECTRICITY',
      suggestedDepartmentName: 'Electricity & Public Lighting Dept',
      suggestedAction: 'Replace fuse and LED power supply unit.',
    },
    upvotes: 32,
    hasUpvoted: false,
    commentsCount: 3,
    history: [
      {
        id: 'h-401',
        status: 'PENDING',
        actorName: 'Aarav Mehta',
        note: 'Submitted ticket.',
        timestamp: '2026-08-07T19:00:00Z',
      },
    ],
    createdAt: '2026-08-07T19:00:00Z',
    updatedAt: '2026-08-07T19:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n-1',
    title: 'Proof-of-Work Verification Required',
    message: 'Sanitation Supervisor Sunil Gupta marked ticket TICK-GARB-3312 as resolved. Please review the after-photo and verify.',
    ticketId: 'TICK-GARB-3312',
    type: 'STATUS_CHANGE',
    read: false,
    createdAt: '10 mins ago',
  },
  {
    id: 'n-2',
    title: 'Senior Engineer Assigned',
    message: 'Your complaint TICK-ROAD-8841 has been assigned to Er. Ramesh Kumar (Senior PWD Inspector).',
    ticketId: 'TICK-ROAD-8841',
    type: 'ASSIGNMENT',
    read: true,
    createdAt: '2 hours ago',
  },
  {
    id: 'n-3',
    title: 'Duplicate Report Merged',
    message: '186 citizen reports were merged into your complaint TICK-ROAD-8841. Priority escalated to 96/100.',
    ticketId: 'TICK-ROAD-8841',
    type: 'DUPLICATE_MERGE',
    read: true,
    createdAt: '4 hours ago',
  },
  {
    id: 'n-4',
    title: 'Achievement Unlocked: Gold Citizen Badge!',
    message: 'Congratulations! You reached 480 Citizen Reputation Points and unlocked Gold Citizen status.',
    type: 'ACHIEVEMENT',
    read: true,
    createdAt: '1 day ago',
  },
];

export const INITIAL_AUDIT_LOGS: SystemAuditLog[] = [
  {
    id: 'log-101',
    actor: 'AI Spatial Merge Engine',
    action: 'DUPLICATE_MERGE_TRIGGERED',
    resource: 'Complaint #TICK-ROAD-8841',
    details: 'Merged 186 duplicate spatial points in 150m radius. Priority boosted from 78 to 96.',
    timestamp: '2026-08-07 15:10:02',
  },
  {
    id: 'log-102',
    actor: 'Er. Rajesh Varma (PWD Head)',
    action: 'ENGINEER_DISPATCH',
    resource: 'Complaint #TICK-ROAD-8841',
    details: 'Assigned Er. Ramesh Kumar with SLA limit 12 hours.',
    timestamp: '2026-08-07 16:00:15',
  },
  {
    id: 'log-103',
    actor: 'AI Vision Core',
    action: 'CLASSIFICATION_COMPLETE',
    resource: 'Image #IMG-9912',
    details: 'Category: DRAINAGE_PROBLEM, Severity: 90%, Confidence: 95%',
    timestamp: '2026-08-07 11:00:05',
  },
];
